# -*- coding: utf-8 -*-
import Logica

def testSuitePegarProximaPosicao():
    print("Testando movimentos na ponta superior da estrela:")
    testaPegarProximaPosicao(1,1,"dl",False,2,1)
    testaPegarProximaPosicao(1,1,"dl",True,3,1)
    testaPegarProximaPosicao(1,1,"dr",False,2,2)
    testaPegarProximaPosicao(1,1,"dr",True,3,3)
    testaPegarProximaPosicao(4,2,"l",False,4,1)
    testaPegarProximaPosicao(4,2,"r",False,4,3)
    testaPegarProximaPosicao(4,2,"l",True,4,0)
    testaPegarProximaPosicao(4,2,"r",True,4,4)
    testaPegarProximaPosicao(4,2,"ul",False,3,1)
    testaPegarProximaPosicao(4,2,"ur",False,3,2)
    print()

    print("Testando movimentos na ponta inferior da estrela:")
    testaPegarProximaPosicao(17,1,"ul",False,16,1)
    testaPegarProximaPosicao(17,1,"ul",True,15,1)
    testaPegarProximaPosicao(17,1,"ur",False,16,2)
    testaPegarProximaPosicao(17,1,"ur",True,15,3)
    testaPegarProximaPosicao(14,2,"dl",False,15,1)
    testaPegarProximaPosicao(14,2,"dl",True,16,0)
    testaPegarProximaPosicao(14,2,"dr",False,15,2)
    testaPegarProximaPosicao(14,2,"dr",True,16,2)
    testaPegarProximaPosicao(14,2,"l",False,14,1)
    testaPegarProximaPosicao(14,2,"r",False,14,3)
    testaPegarProximaPosicao(14,2,"l",True,14,0)
    testaPegarProximaPosicao(14,2,"r",True,14,4)
    print()

    print("Testando movimentos na 2a faixa da estrela:")
    testaPegarProximaPosicao(7,4,"ul",False,6,4)
    testaPegarProximaPosicao(7,4,"ul",True,5,4)
    testaPegarProximaPosicao(7,4,"ur",False,6,5)
    testaPegarProximaPosicao(7,4,"ur",True,5,6)
    testaPegarProximaPosicao(7,4,"dl",False,8,3)
    testaPegarProximaPosicao(7,4,"dl",True,9,2)
    testaPegarProximaPosicao(7,4,"dr",False,8,4)
    testaPegarProximaPosicao(7,4,"dr",True,9,4)
    testaPegarProximaPosicao(7,2,"l",False,7,1)
    testaPegarProximaPosicao(7,2,"r",False,7,3)
    testaPegarProximaPosicao(7,2,"l",True,7,0)
    testaPegarProximaPosicao(7,2,"r",True,7,4)
    print()

    print("Testando movimentos na 3a faixa da estrela:")
    testaPegarProximaPosicao(11,4,"ul",False,10,3)
    testaPegarProximaPosicao(11,4,"ul",True,9,2)    
    testaPegarProximaPosicao(11,4,"ur",False,10,4)
    testaPegarProximaPosicao(11,4,"ur",True,9,4)
    testaPegarProximaPosicao(11,4,"dl",False,12,4)
    testaPegarProximaPosicao(11,4,"dl",True,13,4)
    testaPegarProximaPosicao(11,4,"dr",False,12,5)
    testaPegarProximaPosicao(11,4,"dr",True,13,6)
    testaPegarProximaPosicao(11,2,"l",False,11,1)
    testaPegarProximaPosicao(11,2,"r",False,11,3)
    testaPegarProximaPosicao(11,2,"l",True,11,0)
    testaPegarProximaPosicao(11,2,"r",True,11,4)
    print()

    print("Testando movimentos entre faixa 1 e 2 da estrela:")
    testaPegarProximaPosicao(4,3,"dl",False,5,7)
    testaPegarProximaPosicao(4,3,"dl",True,6,6)
    testaPegarProximaPosicao(4,3,"dr",False,5,8)
    testaPegarProximaPosicao(4,3,"dr",True,6,8)
    testaPegarProximaPosicao(3,3,"dl",True,5,7)
    testaPegarProximaPosicao(3,3,"dr",True,5,9)
    print()

    print("Testando movimentos entre faixa 4 e 3 da estrela:")
    testaPegarProximaPosicao(14,2,"ul",False,13,6)
    testaPegarProximaPosicao(14,2,"ul",True,12,5)
    testaPegarProximaPosicao(14,2,"ur",False,13,7)
    testaPegarProximaPosicao(14,2,"ur",True,12,7)
    testaPegarProximaPosicao(15,2,"ul",True,13,6)
    testaPegarProximaPosicao(15,2,"ur",True,13,8)
    print()

    print("Testando movimentos entre faixa 2 e 1 da estrela:")
    testaPegarProximaPosicao(5,7,"ul",False,4,2)
    testaPegarProximaPosicao(5,7,"ul",True,3,1)
    testaPegarProximaPosicao(5,7,"ur",False,4,3)
    testaPegarProximaPosicao(5,7,"ur",True,3,3)
    testaPegarProximaPosicao(6,6,"ul",True,4,1)
    testaPegarProximaPosicao(6,6,"ur",True,4,3)
    print()

    print("Testando movimentos entre faixa 3 e 4 da estrela:")
    testaPegarProximaPosicao(13,7,"dl",False,14,2)
    testaPegarProximaPosicao(13,7,"dr",False,14,3)
    testaPegarProximaPosicao(13,7,"dl",True,15,1)
    testaPegarProximaPosicao(13,7,"dr",True,15,3)
    testaPegarProximaPosicao(12,7,"dl",True,14,2)
    testaPegarProximaPosicao(12,7,"dr",True,14,4)
    print()

def testaPegarProximaPosicao(linha, coluna, direcao, salto, linhaEsperada, colunaEsperada):
    res = Logica.pegarProximaPosicao(linha,coluna,direcao,salto)
    if res[0] == linhaEsperada and res[1] == colunaEsperada:
        print("OK: ",end="")
    else:
        print("FAIL: ",end="")
    print("Partindo de "+str(linha)+"-"+str(coluna)+"-"+direcao+"(salto="+str(salto)+"), a posição esperada deveria ser "+str(linhaEsperada)+"-"+str(colunaEsperada)+", e o resultado foi ==> "+str(res[0])+"-"+str(res[1]))


testSuitePegarProximaPosicao()
